### ISSUE TITLE
Работа программером в Майкопе

### ISSUE THREAD

**Issue by alexnov-tech** [ktoyou/LibRrdSharp#1]
Привет! Я нашел ссылку на твой гитхаб на hh.ru. Я руководитель отдела ИТ на крупном заводе в Майкопе, у нас много проектов, связанных с автоматизацией бизнеса и производства. Есть команда программистов и айтишников. Я ищу еще одного программиста. Тебе это интересно?

**Comment by ktoyou** [comment]
> Привет! Я нашел ссылку на твой гитхаб на hh.ru. Я руководитель отдела ИТ на крупном заводе в Майкопе, у нас много проектов, связанных с автоматизацией бизнеса и производства. Есть команда программистов и айтишников. Я ищу еще одного программиста. Тебе это интересно?

Здравствуйте. Удивительно, не думал, что напишут прям под репозиторием. Ну, смотря какие условия, и так далее.

**Comment by alexnov-tech** [comment]
Ну других контактов я не вижу, к сожалению. Напиши мне на почту (4239520собакамэилру), я опишу подробнее про работу.

**Comment by ktoyou** [comment]
> Ну других контактов я не вижу, к сожалению. Напиши мне на почту (4239520собакамэилру), я опишу подробнее про работу.

Можете мне в телегу отписать, ник: @atfaive
